import React from 'react';
import styled from '@emotion/styled';

const H1 = styled.h1`
  text-align: center;
`;

export default function Index() {
  return (
    <div>
      <H1>Home</H1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec turpis ligula, eleifend vel nunc id, porttitor eleifend ex. Proin auctor, orci a iaculis molestie, quam urna eleifend lectus, lacinia tempus diam sem et lorem. Mauris eleifend est non ligula egestas, vel vehicula mi consectetur. Donec sit amet tristique est. Cras placerat faucibus turpis, ut pretium leo euismod sed. Vivamus eu gravida nibh, ac egestas neque. Fusce pellentesque ultricies tincidunt. Vestibulum a turpis eget nisl aliquet varius quis nec ligula. Nam rhoncus ullamcorper orci. Ut quis mauris at elit dictum egestas id vitae sapien. In ut viverra purus. Donec suscipit sollicitudin mauris, id rutrum neque mollis id. Praesent malesuada nisl ante, et porttitor leo tincidunt id. In bibendum nec dolor nec posuere. Mauris malesuada nisl est, ut vestibulum odio sodales vel. In pulvinar dui at lacus lacinia pharetra vitae et arcu.</p>
      <p>Cras accumsan ligula dolor, sed blandit libero condimentum non. In ut ligula ut sapien vestibulum auctor quis sed urna. Morbi blandit, felis eu luctus laoreet, nulla orci ullamcorper tellus, sit amet consectetur sem sem ut leo. Vestibulum laoreet lectus arcu, vel facilisis nisl pellentesque eu. Curabitur in varius nunc, eget viverra mi. Nullam eget posuere justo. Fusce interdum arcu vitae est consequat, sit amet consequat eros suscipit. In non urna imperdiet, viverra magna at, ultrices nibh.</p>
      <p>Proin in accumsan nunc, ac fermentum felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam viverra eros nisi, sed semper dui commodo ut. Ut lacinia eleifend nunc, sed volutpat nisl porttitor id. Nullam eu tortor vel magna fringilla convallis. Ut sollicitudin magna ornare enim viverra vestibulum. Aenean fringilla ex eget dolor dictum ultricies. Morbi ut faucibus augue. Nulla scelerisque nisi faucibus mattis tincidunt. Phasellus tempor turpis turpis, a cursus odio imperdiet sed. Cras imperdiet tempus orci, a dignissim turpis tincidunt sit amet. Ut ut tellus vitae ante iaculis condimentum sed nec metus. Nunc placerat mattis ligula sed ultricies. Nunc congue ante dolor, vitae egestas urna aliquet ac. Duis ornare malesuada lectus sit amet blandit. In elit justo, tristique ac facilisis id, tempus ac felis.</p>
      <p>Quisque porttitor fermentum dolor sed convallis. In hac habitasse platea dictumst. Phasellus vel ex vitae eros feugiat placerat euismod vitae massa. Nulla aliquam vitae tellus tincidunt fermentum. Suspendisse vel euismod nunc, quis facilisis ipsum. Proin dolor ante, aliquam non ipsum eu, sodales volutpat enim. Nullam condimentum velit id velit sollicitudin venenatis.</p>
      <p>Mauris tempor pulvinar ex sed suscipit. Curabitur sed diam in tellus vulputate sagittis nec tempor nibh. Fusce mollis posuere ultrices. Nulla vel sagittis ante. Integer interdum cursus dolor, ac dictum mauris consequat sit amet. Nunc vitae dui in enim interdum hendrerit sed vitae tortor. Pellentesque porta ut augue in congue. Integer dolor orci, semper vitae vulputate ac, semper ut magna. Donec sit amet ultricies enim, sed bibendum sapien. Phasellus dignissim id odio nec auctor. Aenean non libero a felis dapibus pellentesque nec ut quam. Vestibulum elementum magna sit amet lacus volutpat hendrerit. Maecenas dictum lacus eget nisl consectetur, ornare luctus augue venenatis. Proin aliquet lacus a suscipit sodales. Donec et commodo felis.</p>
    </div>
  );
}